# These are supported funding mode/storage/emulated/0/Android/media/de.danoeh.antennapod/full-logs.txt
/storage/emulated/0/Android/media/com.javiersantos.mlmanager/com.tdcm.trueidapp_3.44.0.apks
/storage/emulated/0/Android/media/com.javiersantos.mlmanager/ktbcs.netbank_15.3.5.apks
/storage/emulated/0/Android/media/com.javiersantos.mlmanager/com.twitter.android_10.86.0-release.0.apks
/storage/emulated/0/Android/media/com.javiersantos.mlmanager/com.strava_404.11.apks
/storage/emulated/0/Android/media/com.javiersantos.mlmanager/com.linkedin.android_4.1.1049.apks
/storage/emulated/0/Android/media/com.javiersantos.mlmanager/com.dropbox.android_418.2.2.apks
/storage/emulated/0/Android/media/com.javiersantos.mlmanager/com.google.android.apps.subscriptions.red_1.256.738883643.apks
l platforms

custom: ['https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7ELM486P7XKKG', 'https://github.com/sponsors/v1s1t0r1sh3r3', 'https://airgeddon.creator-spring.com/', 'https://www.buymeacoffee.com/v1s1t0r']
