# These are supported funding m[![.github/workflows/master.yml](https://github.com/DAKADI40/airgeddon/actions/workflows/master.yml/badge.svg)](https://github.com/DAKADI40/airgeddon/actions/workflows/master.yml)odel platforms

custom: ['https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7ELM486P7XKKG', 'https://github.com/sponsors/v1s1t0r1sh3r3', 'https://airgeddon.creator-spring.com/', 'https://www.buymeacoffee.com/v1s1t0r']
